In [2]:
from matplotlib import pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import *
from tensorflow.keras.activations import *
from tensorflow.keras.datasets import *
from tensorflow.keras.metrics import *
from tensorflow.keras.optimizers import *
from tensorflow.keras.losses import *
from tensorflow.keras.layers import *

In [3]:
def create_model():
    model = Sequential()
    model.add(Dense(1024, activation=relu, input_dim=32*32*3))
    model.add(Dropout(0.25))
    model.add(Dense(512, activation=relu))
    model.add(Dropout(0.25))
    model.add(Dense(256, activation=relu))
    model.add(Dropout(0.2))
    model.add(Dense(128, activation=relu))
    model.add(Dropout(0.2))
    model.add(Dense(64, activation=relu))
    model.add(Dropout(0.1))
    model.add(Dense(10, activation=softmax))

    model.compile(optimizer=Adam(),
                  loss=categorical_crossentropy,
                  metrics=[categorical_accuracy])

    return model


In [4]:
if __name__ == "__main__":
    (x_train, y_train), (x_val, y_val) = cifar10.load_data()

    print("Before reshaping ...")

    print(x_train.shape)
    print(y_val.shape)

Before reshaping ...
(50000, 32, 32, 3)
(10000, 1)


In [5]:
y_train = tf.compat.v1.keras.utils.to_categorical(y_train)
y_val = tf.compat.v1.keras.utils.to_categorical(y_val)

x_train = np.reshape(x_train, (-1, 32 * 32 * 3)) / 255.0
x_val = np.reshape(x_val, (-1, 32 * 32 * 3)) / 255.0

print(x_train)
print("After reshaping ...")

print(x_train.shape)
print(x_val.shape)


[[0.23137255 0.24313725 0.24705882 ... 0.48235294 0.36078431 0.28235294]
 [0.60392157 0.69411765 0.73333333 ... 0.56078431 0.52156863 0.56470588]
 [1.         1.         1.         ... 0.31372549 0.3372549  0.32941176]
 ...
 [0.1372549  0.69803922 0.92156863 ... 0.04705882 0.12156863 0.19607843]
 [0.74117647 0.82745098 0.94117647 ... 0.76470588 0.74509804 0.67058824]
 [0.89803922 0.89803922 0.9372549  ... 0.63921569 0.63921569 0.63137255]]
After reshaping ...
(50000, 3072)
(10000, 3072)


In [ ]:
m = create_model()
print(m.summary())

history = m.fit(x_train, y_train,
                validation_data=(x_val, y_val),
                epochs=200,
                batch_size=64)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1024)              3146752   
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               524800    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)               131328    
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               3

50000/50000 [==============================] - 4s 83us/sample - loss: 1.6114 - categorical_accuracy: 0.4240 - val_loss: 1.5612 - val_categorical_accuracy: 0.4493
Epoch 38/200
50000/50000 [==============================] - 4s 82us/sample - loss: 1.6172 - categorical_accuracy: 0.4212 - val_loss: 1.5421 - val_categorical_accuracy: 0.4564
Epoch 39/200
50000/50000 [==============================] - 4s 80us/sample - loss: 1.6055 - categorical_accuracy: 0.4252 - val_loss: 1.5496 - val_categorical_accuracy: 0.4471
Epoch 40/200
50000/50000 [==============================] - 4s 81us/sample - loss: 1.6073 - categorical_accuracy: 0.4280 - val_loss: 1.5341 - val_categorical_accuracy: 0.4551
Epoch 41/200
50000/50000 [==============================] - 4s 83us/sample - loss: 1.6061 - categorical_accuracy: 0.4270 - val_loss: 1.5377 - val_categorical_accuracy: 0.4620
Epoch 42/200
50000/50000 [==============================] - 4s 83us/sample - loss: 1.5985 - categorical_accuracy: 0.4280 - val_loss: 1.577

In [ ]:
plt.plot(history.history['categorical_accuracy'], label='categorical_accuracy')
plt.plot(history.history['val_categorical_accuracy'], label='val_categorical_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')